# -*- mode: ruby -*-
# vi: set ft=ruby :

BRIDGE_NETWORK = "Realtek RTL8852AE WiFi 6 802.11ax PCIe Adapter"

### Master (SysAdmin Machine)
MASTER_RAM = 4096
MASTER_CPU = 4

### Cluster nodernetes
N = 2
RAM = 2048
CPU = 2
PRIVATE_IP_PREFIX = "192.168.130."
PUBLIC_IP_PREFIX = "192.168.1."

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  (1..N).each do |machine_id|
    config.vm.define "node-0#{machine_id}" do |node|
      node.vm.box = "peru/ubuntu-20.04-server-amd64"
      node.vm.hostname = "node-0#{machine_id}"
      node.vm.provider "virtualbox" do |v|
        v.name = "node-0#{machine_id}"
        v.memory = RAM
        v.cpus = CPU
      end
      node.vm.network "public_network", bridge: BRIDGE_NETWORK, ip: "#{PUBLIC_IP_PREFIX}#{170+machine_id}"
      node.vm.network "private_network", ip: "#{PRIVATE_IP_PREFIX}#{170+machine_id}"
      # config.vm.provision "ansible" do |ansible|
      #   ansible.playbook = "ansible-playbook/site_staging.yml"
      # end
    end
  end

  config.vm.define "master" do |master|
    master.vm.box = "peru/ubuntu-20.04-server-amd64"
    master.vm.provider "virtualbox" do |v|
      v.name = "master"
      v.memory = MASTER_RAM
      v.cpus = MASTER_CPU
    end
    master.vm.network "public_network", bridge: BRIDGE_NETWORK, ip: "#{PUBLIC_IP_PREFIX}#{170}"
    master.vm.network "private_network", ip: "#{PRIVATE_IP_PREFIX}#{170}"
  end

end