---
- name: Install and configure Kubernetes Master Node
  hosts: master
  gather_facts: yes
  become: yes
  
  roles:
  - common
  - docker
  - kubernetes


- name: Install and configure Kubernetes Workers Node
  hosts: node
  gather_facts: yes
  become: yes
  
  roles:
  - common
  - docker
  - kubernetes