---
# tasks file for Docker

- name: download package information from all configured sources
  command: apt-get update
  become: yes
  ignore_errors: true

- name: remove old docker keys
  command: rm /usr/share/keyrings/docker-archive-keyring.gpg
  ignore_errors: true
  become: yes

- name: Add Docker's official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: set up the docker stable repository
  shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    executable: /bin/bash

- name: Update apt package index
  command: sudo apt-get update
  ignore_errors: true

- name: install docker
  command:  apt-get install -y docker-ce docker-ce-cli containerd.io
  ignore_errors: true

- name: change docker cgroup driver to systemd 
  shell: |
    cat <<EOF | sudo tee /etc/docker/daemon.json
    {
      "exec-opts": ["native.cgroupdriver=systemd"]
    }
    EOF
  args:
    executable: /bin/bash

- name: updating the systemd configuration
  command: systemctl daemon-reload

- name: restart docker service
  command: systemctl restart docker
